# Generated by Django 6.0.2 on 2026-02-24 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('material_desejado', models.TextField(blank=True, null=True)),
                ('orcamento_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('negociacao', 'Em negociação'), ('aceito', 'Aceito'), ('encerrado', 'Encerrado')], default='aberto', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_feitos', to=settings.AUTH_USER_MODEL)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_recebidos', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo', models.CharField(max_length=100)),
                ('materiais_inclusos', models.BooleanField(default=False)),
                ('observacoes', models.TextField()),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='enviada', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='servicos.pedido')),
            ],
        ),
    ]
