# Generated by Django 6.0.2 on 2026-02-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='formas_pagamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='horario_atendimento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
